// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByrPpJhbtdLp9kz7-gr5mXLu3GtL5J8s8',
    appId: '1:888852099234:web:517d2c8f4b5fb846d9a7fb',
    messagingSenderId: '888852099234',
    projectId: 'phone-firebase-8bd5d',
    authDomain: 'phone-firebase-8bd5d.firebaseapp.com',
    storageBucket: 'phone-firebase-8bd5d.appspot.com',
    measurementId: 'G-31JE89F2BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7T5gZFMMejvXry3iJMxgMd2hA57T8gU4',
    appId: '1:888852099234:android:7ebb6736e97945ccd9a7fb',
    messagingSenderId: '888852099234',
    projectId: 'phone-firebase-8bd5d',
    storageBucket: 'phone-firebase-8bd5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDICSRHjltxr-Xp5Ki_6oGeMgc5w7grvnY',
    appId: '1:888852099234:ios:16336548eb50ec6bd9a7fb',
    messagingSenderId: '888852099234',
    projectId: 'phone-firebase-8bd5d',
    storageBucket: 'phone-firebase-8bd5d.appspot.com',
    iosClientId: '888852099234-2nhe561d67s7qmt154rptud9fscv86us.apps.googleusercontent.com',
    iosBundleId: 'net.redeemx.patron.m-login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDICSRHjltxr-Xp5Ki_6oGeMgc5w7grvnY',
    appId: '1:888852099234:ios:8ea1572b9945be38d9a7fb',
    messagingSenderId: '888852099234',
    projectId: 'phone-firebase-8bd5d',
    storageBucket: 'phone-firebase-8bd5d.appspot.com',
    iosClientId: '888852099234-1nfjub8qa7n7egkn56lfi8k6qrl4qu81.apps.googleusercontent.com',
    iosBundleId: 'net.redeemx.patron.mlogin',
  );
}
